# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    tags:
      - "*"
env:
  RELEASE_VERSION: ${{ github.ref }}
jobs:
  build-wheel:
    name: build-wheel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      -
        name: Build and upload
        env:
          PYPI_API_USERNAME: ${{ secrets.PYPI_API_USERNAME }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: pip install -r requirements.txt && python -m build && python -m twine upload -u ${PYPI_API_USERNAME} -p ${PYPI_API_TOKEN} --verbose --skip-existing dist/*